version: '2'

services:

### Applications Code Container #############################

  ruby:
    volumes:
      - app-sync:/app:nocopy # nocopy is required
      - bundle-sync:/usr/local/bundle:nocopy # nocopy is required

### Volumes Setup #############################################

volumes:
  app-sync:
    external: true
  bundle-sync:
    external: true
